// Generated by OpenNext during cf:build.
// @ts-ignore Generated module does not exist before build.
import nextWorker from './.open-next/worker.js';
import type { ExecutionContext, ScheduledController, MessageBatch } from '@cloudflare/workers-types';
import type { Env } from './src/lib/env';

export default {
  fetch(request: Request, env: Env, ctx: ExecutionContext) {
    return nextWorker.fetch(request, env, ctx);
  },
  async scheduled(_event: ScheduledController, _env: Env, _ctx: ExecutionContext) {
    // Real subscription/monthly media jobs are deliberately out of this validation slice.
  },
  async queue(batch: MessageBatch<unknown>, _env: Env, _ctx: ExecutionContext) {
    // Acknowledge mock queue messages only; real video transfers are not implemented.
    for (const message of batch.messages) message.ack();
  },
};
