CREATE TABLE user (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, email_verified INTEGER NOT NULL DEFAULT 0, image TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE TABLE session (id TEXT PRIMARY KEY, expires_at INTEGER NOT NULL, token TEXT NOT NULL UNIQUE, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, ip_address TEXT, user_agent TEXT, user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE);
CREATE INDEX session_user_id_idx ON session(user_id);
CREATE TABLE account (id TEXT PRIMARY KEY, account_id TEXT NOT NULL, provider_id TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES user(id) ON DELETE CASCADE, access_token TEXT, refresh_token TEXT, id_token TEXT, access_token_expires_at INTEGER, refresh_token_expires_at INTEGER, scope TEXT, password TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX account_user_id_idx ON account(user_id);
CREATE TABLE verification (id TEXT PRIMARY KEY, identifier TEXT NOT NULL, value TEXT NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL);
CREATE INDEX verification_identifier_idx ON verification(identifier);
CREATE TABLE credit_lot (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, source TEXT NOT NULL, source_id TEXT NOT NULL, granted INTEGER NOT NULL CHECK(granted > 0), remaining INTEGER NOT NULL CHECK(remaining >= 0 AND remaining <= granted), expires_at INTEGER, created_at INTEGER NOT NULL, UNIQUE(source, source_id));
CREATE INDEX credit_lot_spend ON credit_lot(user_id, expires_at);
CREATE TABLE credit_entry (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, kind TEXT NOT NULL CHECK(kind IN ('grant','consume','refund','reclaim','expire','adjust')), amount INTEGER NOT NULL, requested INTEGER, ref_id TEXT, idem_key TEXT NOT NULL UNIQUE, created_at INTEGER NOT NULL, CHECK(kind <> 'consume' OR (requested > 0 AND -amount = requested)));
CREATE TABLE credit_alloc (entry_id TEXT NOT NULL, lot_id TEXT NOT NULL REFERENCES credit_lot(id), amount INTEGER NOT NULL CHECK(amount > 0), PRIMARY KEY(entry_id, lot_id));
CREATE TABLE video_task (id TEXT PRIMARY KEY, user_id TEXT NOT NULL, cost INTEGER NOT NULL CHECK(cost > 0), status TEXT NOT NULL CHECK(status IN ('reserved','submitted','processing','succeeded','canceled','refunded')), consume_entry_id TEXT NOT NULL UNIQUE);
