'use client';

import React, { useEffect, useRef, useState, type ReactNode } from 'react';
import Link from 'next/link';
import { FaFacebookF, FaLinkedinIn, FaRedditAlien, FaTelegram, FaWhatsapp, FaXTwitter } from 'react-icons/fa6';
import { Check, ChevronDown, CircleHelp, Copy, Gift, Mail, MessageCircle, Share2, X } from 'lucide-react';
import { routePath } from '@/lib/route-paths';
import { useDismissableLayer } from '@/lib/use-dismissable-layer';
import type en from '@site/messages/en';
import { dailyRewardState } from './account-popover-state';

export type AccountCopy = (typeof en)['account'];
export type Plan = { id: string; billing: 'once' | 'year'; credits: number; amount: string; currency: string; name: string };
export type Network = 'Facebook' | 'X' | 'WhatsApp' | 'LinkedIn' | 'Telegram' | 'Reddit';
export type Settings = { checkIn: { enabled: boolean; credits: number }; share: { enabled: boolean; credits: number; maxSubmissions: number }; referral: { enabled: boolean; inviterCredits: number; friendCredits: number }; contactEmail: string; feedbackEmail: string; commercialUseHref: string; shareNetworks: readonly Network[]; sharePostNetworks: readonly Network[]; icons: { checkin: string; share: string; invite: string; contact: string; feedback: string } };
export type Activity = { balance: number; referralCode: string; checkInDays: string[]; submissions: { id: string; url: string; status: string; created_at: number }[]; referralCount: number; purchases: { source_id: string; granted: number; created_at: number }[]; leaderboard: { name: string; total: number }[] };
export type Dialog = 'checkin' | 'share' | 'invite' | 'contact' | 'feedback' | 'plans' | 'invoices' | null;

const socialIcons = { Facebook: FaFacebookF, X: FaXTwitter, WhatsApp: FaWhatsapp, LinkedIn: FaLinkedinIn, Telegram: FaTelegram, Reddit: FaRedditAlien };
function SocialIcon({ name }: { name: Network }) { const Icon = socialIcons[name]; return <Icon aria-hidden="true" className={`account-social-mark ${name.toLowerCase()}`} />; }

function PopupDialog({ title, closeLabel, onClose, children, wide = false, variant }: { title: string; closeLabel: string; onClose: () => void; children: ReactNode; wide?: boolean; variant: NonNullable<Dialog> }) {
  const ref = useRef<HTMLDivElement>(null);
  const overlay = useRef<HTMLDivElement>(null);
  useDismissableLayer({ active: true, area: ref, backdrop: overlay, onClose, trapFocus: true });
  useEffect(() => { const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = overflow; }; }, []);
  return <div className="account-overlay" ref={overlay}><div className={`account-dialog${wide ? ' wide' : ''} account-${variant}-dialog`} ref={ref} role="dialog" aria-modal="true" aria-labelledby="account-dialog-title"><button type="button" className="account-close" aria-label={closeLabel} onClick={onClose}><X size={20} /></button><h2 id="account-dialog-title">{title}</h2>{children}</div></div>;
}

function DialogHero({ icon, kicker, title, lead, invite = false }: { icon: ReactNode; kicker: ReactNode; title: string; lead: string; invite?: boolean }) {
  return <div className={`account-hero account-checkin-hero${invite ? ' account-invite-hero' : ''}`}><span className="account-hero-icon">{icon}</span><div><span className="account-kicker">{kicker}</span><h2>{title}</h2><p>{lead}</p></div></div>;
}

export function AccountDialogs({ dialog, onClose, copy, labels, settings, plans, activity, busy, error, notice, locale, dateLocale, siteUrl, brand, icons, onCopyText, onAction }: {
  dialog: NonNullable<Dialog>; onClose: () => void; copy: AccountCopy; labels: { credits: string }; settings: Settings; plans: Plan[];
  activity: Activity | null; busy: boolean; error: string; notice: string; locale: string; dateLocale: string; siteUrl: string; brand: string;
  icons: { checkin: ReactNode; share: ReactNode; invite: ReactNode };
  onCopyText: (text: string) => void; onAction: (kind: 'checkin' | 'share', postUrl?: string) => Promise<boolean>;
}) {
  const [postUrl, setPostUrl] = useState('');
  const [planBilling, setPlanBilling] = useState<'once' | 'year'>('once');
  const [detailsOpen, setDetailsOpen] = useState(false);
  const { claimedToday, completed: streakDays, nextClaimAt } = dailyRewardState(activity?.checkInDays ?? [], new Date());
  const nextClaim = nextClaimAt.toLocaleString(dateLocale);
  const link = `${siteUrl}${routePath(locale, 'home')}?ref=${activity?.referralCode ?? ''}`;
  const shareText = `${brand} ${siteUrl}`;
  const shareTargets = (url: string) => [
    { name: 'Reddit', href: `https://www.reddit.com/submit?url=${encodeURIComponent(url)}&title=${encodeURIComponent(brand)}` },
    { name: 'X', href: `https://x.com/intent/post?text=${encodeURIComponent(brand)}&url=${encodeURIComponent(url)}` },
    { name: 'Facebook', href: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}` },
    { name: 'LinkedIn', href: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}` },
    { name: 'WhatsApp', href: `https://api.whatsapp.com/send?text=${encodeURIComponent(`${brand} ${url}`)}` },
    { name: 'Telegram', href: `https://t.me/share/url?url=${encodeURIComponent(url)}&text=${encodeURIComponent(brand)}` },
  ];
  const networks = (url: string, names: readonly Network[]) => names.map(name => shareTargets(url).find(item => item.name === name)!);
  return <PopupDialog title={{ checkin: copy.checkinTitle, share: copy.shareTitle, invite: copy.inviteTitle, contact: copy.contactTitle, feedback: copy.feedbackTitle, plans: copy.plansTitle, invoices: copy.invoiceTitle }[dialog]} closeLabel={copy.close} onClose={onClose} wide={dialog === 'invite' || dialog === 'plans' || dialog === 'checkin' || dialog === 'share'} variant={dialog}>
    {dialog === 'checkin' && <><DialogHero icon={icons.checkin} kicker={copy.checkinKicker} title={copy.daily} lead={copy.checkinLead} /><div className="account-body account-checkin-body"><div><div className="account-heading"><b>{copy.checkinRewards}</b><span>{streakDays}/7 {copy.days}</span></div><div className="account-days">{Array.from({ length: 7 }, (_, index) => { const done = index < streakDays; const current = index === streakDays; return <div key={index} className={done ? 'complete' : current ? 'current' : 'future'}><small>{copy.day} {index + 1}</small>{done ? <Check aria-label={copy.claimed}/> : <strong>+{settings.checkIn.credits}</strong>}</div>; })}</div></div><button className="account-primary" disabled={busy || !activity || claimedToday} onClick={() => onAction('checkin')}>{claimedToday && <Check size={20}/>}{claimedToday ? copy.claimed : busy ? copy.loading : copy.claim}</button>{claimedToday ? <p className="account-next-claim">{copy.nextClaim} {nextClaim}</p> : <p className="account-next-claim">{copy.checkinHint}</p>}{settings.referral.enabled && <section className="account-daily-share"><div className="account-daily-share-intro"><div><span className="account-kicker"><Share2 size={15}/>{copy.inviteShareKicker}</span><h3>{copy.inviteNext}</h3><p>{copy.inviteShareLead}</p></div><button className="account-secondary" disabled={!activity} onClick={() => onCopyText(`${copy.inviteShareLead} ${link}`)}><Copy size={16}/>{copy.copyInvite}</button></div><div className="account-social-grid">{networks(link, settings.shareNetworks).map(item => <a key={item.name} href={activity ? item.href : undefined} target="_blank" rel="noopener noreferrer" aria-disabled={!activity} onClick={event => { if (!activity) event.preventDefault(); }}><SocialIcon name={item.name as Network}/>{item.name}</a>)}</div></section>}<button type="button" className="account-details-toggle" aria-expanded={detailsOpen} onClick={() => setDetailsOpen(open => !open)}><CircleHelp size={14}/>{copy.activityDetails}</button>{detailsOpen && <p className="account-details-content">{copy.activityDetailText} <Link href={routePath(locale, 'credits')} onClick={onClose}>{copy.center}</Link></p>}</div></>}
    {dialog === 'share' && <><DialogHero icon={icons.share} kicker={`+${settings.share.credits}`} title={copy.shareHeroTitle.replace('{credits}', String(settings.share.credits))} lead={copy.shareLead} /><div className="account-body account-share-body"><div className="account-panel"><h3>{copy.publishStep}</h3><p>{copy.publishLead}</p><p><b>{copy.publishAdvice}</b></p><button className="account-primary" onClick={() => onCopyText(shareText)}><Copy size={17}/>{copy.quickCopy}</button><div className="account-sharelinks">{networks(siteUrl, settings.sharePostNetworks).map(item => <a key={item.name} href={item.href} target="_blank" rel="noopener noreferrer" aria-label={item.name}><SocialIcon name={item.name as Network}/></a>)}</div><details><summary>{copy.shareWhere}<ChevronDown size={15}/></summary><p>{copy.shareWhereDetail}</p></details></div><form className="account-panel" onSubmit={event => { event.preventDefault(); void onAction('share', postUrl).then(success => { if (success) setPostUrl(''); }); }}><h3>{copy.submitStep}</h3><p>{copy.submitLead.replace('{credits}', String(settings.share.credits))}</p><div className="account-submit"><input type="url" required value={postUrl} onChange={event => setPostUrl(event.target.value)} placeholder={copy.postPlaceholder} aria-label={copy.submitPost} /><button type="submit" disabled={busy || !activity || activity.submissions.length >= settings.share.maxSubmissions}>{activity && activity.submissions.length >= settings.share.maxSubmissions ? copy.shareLimit : busy ? copy.loading : copy.submit}</button></div></form>{!!activity?.submissions.length && <div className="account-panel account-share-history"><h3>{copy.submissions}</h3>{activity.submissions.map(item => <p className="account-entry" key={item.id}><a href={item.url} target="_blank" rel="noopener noreferrer">{item.url}</a><span>{copy[item.status as 'pending' | 'approved' | 'rejected'] ?? item.status}</span></p>)}</div>}</div></>}
    {dialog === 'invite' && <><DialogHero icon={icons.invite} kicker={`${settings.referral.inviterCredits} ${labels.credits}`} title={copy.inviteTitle} lead={copy.inviteLead} invite /><div className="account-body account-invite-grid"><section className="account-panel account-invite-link"><h3><Gift size={20}/>{copy.referralLink}</h3><p>{copy.inviteLead}</p><div className="account-referral"><span>{activity ? link : copy.loading}</span><button disabled={!activity} onClick={() => onCopyText(link)}><Copy size={15}/>{copy.copyLink}</button></div><div className="account-invite-social"><small>{copy.shareVia}</small><div className="account-sharelinks">{activity && networks(link, settings.shareNetworks).map(item => <a key={item.name} href={item.href} target="_blank" rel="noopener noreferrer" aria-label={item.name}><SocialIcon name={item.name as Network}/></a>)}</div></div></section><section className="account-panel account-invite-rewards"><h3><Gift size={18}/>{copy.yourRewards}</h3><p>{copy.inviteSummary.replace('{inviter}', String(settings.referral.inviterCredits)).replace('{friend}', String(settings.referral.friendCredits))}</p><div className="account-stats"><span>{copy.youGet}<b>+{settings.referral.inviterCredits}</b></span><span>{copy.friendGets}<b>+{settings.referral.friendCredits}</b></span></div><div className="account-invite-totals"><span>{copy.totalEarned}<b>{(activity?.referralCount ?? 0) * settings.referral.inviterCredits}</b></span><span>{copy.referred}<b>{activity?.referralCount ?? 0}</b></span></div><div className="account-invite-rules"><strong>{copy.rewardRules}</strong><p>{copy.referralRules}</p></div></section><section className="account-panel account-invite-leaderboard"><h3>{copy.leaderboard}</h3><p>{copy.leaderboardLead}</p>{activity?.leaderboard.length ? <ol className="account-leaderboard">{activity.leaderboard.map(item => <li key={item.name}>{item.name} <span>{item.total} {copy.referred}</span></li>)}</ol> : <p>{copy.noLeaderboard}</p>}</section><section className="account-panel account-referral-history"><h3>{copy.history}</h3><p>{activity?.referralCount ? `${activity.referralCount} ${copy.referred}` : copy.noReferrals}</p></section></div></>}
    {dialog === 'contact' || dialog === 'feedback' ? <div className="account-body account-contact">{dialog === 'contact' ? <CircleHelp size={28}/> : <MessageCircle size={28}/>}<p>{dialog === 'contact' ? copy.contactLead : copy.feedbackLead}</p><a href={`mailto:${dialog === 'contact' ? settings.contactEmail : settings.feedbackEmail}`}>{dialog === 'contact' ? settings.contactEmail : settings.feedbackEmail}</a></div> : null}
    {dialog === 'plans' && <div className="account-body"><div className="account-tabs">{(['once','year'] as const).map(period => <button key={period} className={planBilling === period ? 'selected' : ''} onClick={() => setPlanBilling(period)}>{copy[period]}</button>)}</div><div className="account-plans">{plans.filter(plan => plan.billing === planBilling).map(plan => <Link key={plan.id} href={routePath(locale, 'pricing')}><h3>{plan.name}</h3><strong>{plan.currency} {plan.amount}</strong><span>{plan.credits} {labels.credits}</span></Link>)}</div><p>{copy.planHint}</p><Link className="account-primary" href={routePath(locale, 'pricing')}>{copy.viewPlans}</Link></div>}
    {dialog === 'invoices' && <div className="account-body"><p>{copy.invoiceLead}</p>{activity?.purchases.length ? activity.purchases.map(item => <div className="account-entry" key={item.source_id}><span><b>{item.source_id}</b><small>{new Date(item.created_at).toLocaleDateString(dateLocale)}</small></span><strong>+{item.granted} {labels.credits}</strong></div>) : <div className="account-panel">{copy.noInvoices}</div>}<a className="account-secondary" href={`mailto:${settings.contactEmail}?subject=${encodeURIComponent(copy.requestInvoice)}`}><Mail size={16}/>{copy.requestInvoice}</a></div>}
    {(error || notice) && <p className={error ? 'account-error' : 'account-message'} role={error ? 'alert' : 'status'}>{error || notice}</p>}
  </PopupDialog>;
}
