export default {
    menu: '账号菜单', buy: '购买积分', daily: '每日签到 · 免费积分', free: '免费', share: '分享赚积分', invite: '邀请好友', contact: '联系我们', feedback: '反馈问题', account: '账号', invoices: '发票与付款记录', center: '积分中心', license: '套餐与商用信息',
    checkinTitle: '每日签到 · 免费积分', checkinLead: '领取一份免费积分，开启下一次创作。', checkinKicker: '每日创作奖励', checkinRewards: '七日创作奖励', days: '天已完成', day: '第', claim: '领取今日免费奖励', claimed: '今日已领取 · 明天再来', nextClaim: '下次领取：', checkinHint: '积分立即加入余额。每个 UTC 自然日可领取一次。', inviteNext: '邀请好友免费创作', inviteShareKicker: '分享每日灵感', inviteShareLead: '分享每日创作奖励，邀请好友一起来签到。', copyInvite: '复制邀请链接', checkinInviteMessage: '我发现一个网站，每天签到就能领取免费创作奖励。来试试吧：', activityDetails: '活动详情', activityDetailText: '每个 UTC 自然日最多领取一次积分。已领取的奖励可在积分历史中查看。',
    shareTitle: '分享赚积分', shareHeroTitle: '分享并获得 {credits} 积分', publishStep: 'A · 发布推荐内容', publishLead: '在公开社区分享本站，审核通过后获得积分。', publishAdvice: '请分享至您真实参与的公开社区。', submitStep: 'B · 提交帖子链接', submitLead: '粘贴公开帖子的链接。审核通过后可获得 {credits} 积分。', shareLead: '在公开社区分享本站。审核通过后获得 {credits} 积分，最多 {limit} 次。' , quickCopy: '快速复制', shareRecommendation: '发现一个可以预览 MiniMax H3 视频和 AI 图片请求、每天签到领免费积分的网站', shareRecommendationNoDaily: '发现一个可以预览 AI 视频和图片创意的网站', otherCommunities: '也可以分享到你真实参与的其他社区', shareCopied: '推荐文案和链接已复制', shareWhere: '可以分享到哪里？', shareWhereDetail: '请发布在你参与的公开社区，帖子无需登录即可访问。', shareGuidelines: ['我们看重真实分享，而不是平台规模。帖子必须公开可见，并发布在有真实内容和成员的活跃社区。', '内容长短不限，简短推荐也可以。', '没有真实内容的空网站或自建论坛不能获得奖励。'], submitPost: '提交公开帖子链接', postPlaceholder: 'https://reddit.com/r/...', submit: '提交', submissions: '我的提交', pending: '待审核', approved: '已通过', rejected: '未通过', shareLimit: '提交次数已达上限',
    inviteTitle: '邀请好友赚积分', inviteKicker: '{credits} 积分', inviteLead: '分享你的邀请链接，每位符合条件并加入 {brand} 的好友都能为你带来 {creditLabel}！', inviteCreditUnit: '积分', referralLink: '获取你的邀请链接', inviteLinkLead: '将以下链接分享给好友。每位通过此链接加入 {brand} 并符合条件的好友，都能为你带来 {credits} 积分。', copyLink: '复制链接', shareVia: '分享到：', history: '邀请记录', refreshHistory: '刷新邀请记录', historyEmptyTitle: '你还没有邀请好友！', historyEmptyLead: '分享你的链接，开始赚取积分。', leaderboard: '全球邀请排行榜', leaderboardTop: '前 3 名', leaderboardLead: '按成功邀请人数排序', leaderboardEmptyTitle: '暂无成功邀请', leaderboardEmptyLead: '成功邀请好友后，这里就会显示排行。', successfulInvites: '位成功邀请', inviteSummary: '每邀请一位好友，你获得 {inviter} 积分，好友获得 {friend} 积分。', totalEarned: '累计获得积分', rewardRules: '奖励规则', noLeaderboard: '暂无成功邀请记录。', noReferrals: '暂无成功邀请，分享链接开始邀请吧。', yourRewards: '你的奖励', youGet: '你获得', friendGets: '好友获得', referred: '已邀请用户', referralRules: ['新好友须在注册后 {hours} 小时内领取邀请奖励。', '每个新账号只能领取一次邀请奖励。', '邀请自己不会获得积分。', '符合条件的好友领取邀请奖励后，积分才会入账。'],
    contactTitle: '联系我们', contactLead: '账号或支付遇到问题？请发邮件给支持团队。', feedbackTitle: '发送反馈', feedbackLead: '通过邮件提交建议或问题。反馈不会自动发放积分。',
    plansTitle: '选择套餐', packName: '积分包', annualName: '年度套餐', once: '积分包', month: '月付套餐', year: '年付套餐', planHint: '前往价格页查看套餐。当前尚未核对匹配的支付商品，暂不能结账。', viewPlans: '查看所有套餐',
    invoiceTitle: '付款记录', invoiceLead: '积分账本中记录的已结算购买。如需税务发票，请附付款编号联系支持。', noInvoices: '暂无购买记录。', requestInvoice: '索取发票',
    copied: '已复制到剪贴板', copyFailed: '无法使用剪贴板，请手动复制链接。', sent: '已提交审核，尚未发放积分。', claimedNotice: '奖励积分已到账。', referralNotice: '邀请奖励已到账。', actionFailed: '操作失败，请重试。', loadFailed: '无法加载账号活动，请重新打开卡片。', close: '关闭', loading: '加载中…',
  };
