export default {
  nav: { brand: 'Awesomejev', navigation: 'Main navigation', home: 'Home', workspace: 'Workspace', credits: 'Credits', language: 'Language', login: 'Sign In', google: 'Continue with Google', github: 'Continue with GitHub', email: 'Use email', orEmail: 'Or continue with email', signIn: 'Sign in', signUp: 'Create account', name: 'Name', password: 'Password', noMethods: 'Sign-in unavailable', logout: 'Sign out', invite: 'Redeem invite', wait: 'Please wait…', close: 'Close', emailLabel: 'Email', authFailed: 'Authentication failed. Please try again.', socialFailed: 'Sign-in could not start. Please try again.', signOutFailed: 'Sign-out failed. Please try again.', inviteInvalid: 'Invalid or exhausted invite code.', inviteRedeemFailed: 'Could not redeem invite code. Please try again.', createdButInviteFailed: 'Account created, but invite redemption failed. Enter your code after signing in.', desktopSignIn: 'Sign in to continue', desktopWaiting: 'Signing in to your app', desktopReturning: 'Returning to your app…', desktopFailed: 'Desktop sign-in could not finish.', verifyTitle: 'Check your email', verifyHint: 'Open the verification link we emailed you before signing in. Check spam if it has not arrived.', verificationSent: 'Verification link sent to', resendVerification: 'Resend verification email', resendFailed: 'Could not send the verification email. Please try again.', verifyLink: 'Open verification page', emailNotVerified: 'Your email is not verified yet. Check your inbox or resend the link.', verifyContinue: 'I have verified my email', forgotPassword: 'Forgot password?', forgotTitle: 'Reset your password', forgotHint: 'Enter the email on your account. We will send one link to choose a new password.', resetSent: 'If an account exists for that email, a reset link is on its way.', resetSendFailed: 'Could not send the reset email. Please try again.', resetTitle: 'Choose a new password', resetHint: 'Enter a new password for your account. It must be at least 8 characters.', newPassword: 'New password', confirmPassword: 'Confirm password', updatePassword: 'Update password', resetSuccess: 'Password updated. Sign in with your new password.', resetInvalid: 'This reset link is invalid or has expired. Request a new one from the sign-in form.', passwordMismatch: 'Those passwords do not match.', resetMailSubject: 'Reset your password for Awesomejev', resetMailLead: 'Open this link to choose a new password:', resetMailAction: 'Reset password', resetMailExpiry: 'This link expires in 1 hour.' },
  hero: {
    title: 'A place to begin the next frame.',
    description: 'Your private workspace is ready. Sign in to see your credits; video creation and checkout are not available yet.',
    detail: 'A preview of the workspace to come.',
    explore: 'Explore workspace',
    openWorkspace: 'Open workspace',
    credits: 'Available credits',
  },
  dashboard: { title: 'Overview', navigation: 'Workspace navigation', preview: 'Preview workspace', signInTitle: 'Sign in to view your workspace', signInDescription: 'Use Sign In in the navigation to access your account and credits.', backHome: 'Back to home', summary: 'Credits are ready to use when video creation becomes available.', nextTitle: 'Your account, all in one place', nextDescription: 'Review your credit balance and grants. Video tools and payments are not available in this preview.', viewCredits: 'View credits' },
  credits: { title: 'Credits', listTitle: 'Credit history', description: 'Credits granted to your account. Only your own records are shown.', balance: 'Available', source: 'Source', granted: 'Granted', remaining: 'Remaining', expires: 'Expires', signup: 'Welcome credits', subscription: 'Subscription', noExpiry: 'No expiration', empty: 'No credit grants yet.' },
};
